steps:
  # Install
- name: 'gcr.io/cloud-builders/npm'
  args: 
  - 'ci'

  # Build
- name: 'gcr.io/cloud-builders/npm'
  args: 
  - 'run'
  - 'build'

  # Deploy
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  args:
  - gcloud
  - functions
  - deploy
  - mail-hml
  - --set-env-vars
  - NODE_ENV=acceptance
  - --runtime=nodejs14
  - --source=.
  - --entry-point=sendEmail
  - --trigger-topic
  - HML_SEND_EMAIL
  - --allow-unauthenticated