steps:
  # Install
- name: 'gcr.io/cloud-builders/npm'
  args: 
  - 'install'

  # Build
- name: 'gcr.io/cloud-builders/npm'
  args: 
  - 'run'
  - 'build'

  # Deploy
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  args:
  - gcloud
  - functions
  - deploy
  - mail
  - --set-env-vars
  - NODE_ENV=production
  - --runtime=nodejs14
  - --source=.
  - --entry-point=sendEmail
  - --trigger-topic
  - SEND_EMAIL
  - --allow-unauthenticated