steps:
  # Install
- name: 'gcr.io/cloud-builders/npm'
  args: 
  - 'install'

  # Build
- name: 'gcr.io/cloud-builders/npm'
  args: 
  - 'run'
  - 'build'

  # Deploy
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  args:
  - gcloud
  - functions
  - deploy
  - mail
  - --runtime=nodejs14
  - --source=app
  - --trigger-http
  - --allow-unauthenticated